# fly.toml app configuration file generated for backend-empty-resonance-8722 on 2025-07-03T09:27:43+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-empty-resonance-8722'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
